### ISSUE TITLE
Feature request: links included in HTML

### ISSUE THREAD

**Issue by jlandahl** [orottier/webpage-rs#18]
Just wondering if you've considered keeping a vector of the links found in the HTML. Seems like a pretty straightforward thing to do since you're already parsing the HTML. I'm starting to look at the source code and will see what it might take to add, maybe come up with a PR in the near future.

**Comment by jlandahl** [comment]
I've looked into this, and it's really easy to add. The only tricky part is dealing with relative URLs. I'm currently writing a simple solution for that (based on `html.url`) but was wondering if you'd be opposed to adding the `url` crate as a dependency to make it more robust?

**Comment by jlandahl** [comment]
Added a PR for this: https://github.com/orottier/webpage-rs/pull/19

I made the "links" feature optional in case you don't want the `url` crate added for whatever reason.

**Comment by orottier** [comment]
Fixed via #19 #21
