### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by llucax** [orottier/webpage-rs#4]
I wonder if making the main structs (de)serializable using `#[derive(Deserializable, Serializable)]` from serde wouldn't be a good addition. I'm new to rust so maybe there is a way to do this easily from outside the crate, so this starts more as a question than a suggestion. I tried to use serde's [*remote* serialization](https://serde.rs/remote-derive.html) but, besides having to mirror all structs from this library, I bumped into `Vec<OpengraphObejct>` and I couldn't find a way easily (in a declarative way) define how to (de)serialize that.

I know adding serde as a dependency might not be desired by all users, but maybe it can be added conditionally through a feature flag?

If you think this is a good idea I might even give it a try as a *rust exercise* :)

PS: Unrelated quick question: any reason why `Webpage` doesn't derive `Debug` too? I notice most structs in the library do.

**Comment by orottier** [comment]
Hi @llucax, those are some valid questions.

I won't be able to make the changes myself this week, but please feel free to open a pull request to address serializability and debug.

You can add the serde dependency as an optional crate feature. This may be a starting point: https://github.com/serde-rs/serde/issues/1021

**Comment by llucax** [comment]
https://github.com/orottier/webpage-rs/pull/5
